apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: rhdh-templates
  description: A collection of Backstage templates for Financial Customer PoC
spec:
  type: url
  targets:
     - https://github.com/RHDH-PoC-MX/rhdh-templates/blob/main/quarkus-stssc-template/template.yaml